language: go

version:
  - 1.9

before_script:
  - if [ ! -e /Applications ]; then mkdir /Applications
  - cd /Applications
  - touch sample1.app sample2.app

script:
  - make test

after_script:
  - cd /Applications
  - rm -f sample1.app sample2.app
