language: go

version:
  - 1.9

before_script:
  - if [ ! -e ~/TmpApplications ]; then mkdir ~/TmpApplications; fi
  - export APP_DIR=~/TmpApplications
  - touch $APP_DIR/sample1.app $APP_DIR/sample2.app

script:
  - make test

after_script:
  - rm -f $APP_DIR/sample1.app $APP_DIR/sample2.app
  - rmdir $APP_DIR
